In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a + a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
3 * a

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
def sumMatrix(A, B):
    A = np.array(A)
    B = np.array(B)

    return A + B

In [ ]:
sumMatrix([1, 2, 3], [4, 5, 6])

array([5, 7, 9])

In [ ]:
def subMatrix(A, B):
    A = np.array(A)
    B = np.array(B)

    return A - B

In [ ]:
def mulMatrix(A, B):
    A = np.array(A)
    B = np.array(B)

    return A * B

In [ ]:
mulMatrix([1, 2, 3], [4, 5, 6])

array([ 4, 10, 18])

In [ ]:
def mulScalarMatrix(A, B):
    A = np.array(A)

    return A * B

In [ ]:
mulScalarMatrix([1, 2, 3], 2)

array([2, 4, 6])

In [ ]:
import numpy as np

class Matrix:

    def sumMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A + B

    def subMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A - B

    def mulMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A * B

    def mulScalarMatrix(A, B):
        A = np.array(A)

        return A * B

In [ ]:
def dotMatrix(A, B):
    A = np.array(A)
    B = np.array(B)

    return A @ B

In [ ]:
dotMatrix([[1, 2], [2, 3]], [[4, 5], [2, 3]])

array([[ 8, 11],
       [14, 19]])

In [ ]:
import numpy as np

class Matrix:

    def sumMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A + B

    def subMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A - B

    def mulMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A * B

    def mulScalarMatrix(A, B):
        A = np.array(A)

        return A * B

    def dotMatrix(A, B):
        A = np.array(A)
        B = np.array(B)

        return A @ B

In [ ]:
def sumMatrix(A, B):
    result = []

    for i in range(len(A)):
        for j in range(len(A[i])):
            if len(A) != len(B) or len(A[i]) != len(B[i]):
                return "행렬 크기를 맞춰주세요"

    for i in range(len(A)):
        tmp = []
        for j in range(len(A[i])):
            tmp.append(A[i][j] + B[i][j])
        result.append(tmp)

    return result

In [ ]:
print(sumMatrix([[1,2], [2,3]], [[3, 4],[5,6]]))

[[4, 6], [7, 9]]


In [ ]:
def subMatrix(A, B):
    result = []

    for i in range(len(A)):
        for j in range(len(A[i])):
            if len(A) != len(B) or len(A[i]) != len(B[i]):
                return "행렬 크기를 맞춰주세요"

    for i in range(len(A)):
        tmp = []
        for j in range(len(A[i])):
            tmp.append(A[i][j] - B[i][j])
        result.append(tmp)

    return result

In [ ]:
def mulMatrix(A, B):
    result = []

    for i in range(len(A)):
        for j in range(len(A[i])):
            if len(A) != len(B) or len(A[i]) != len(B[i]):
                return "행렬 크기를 맞춰주세요"

    for i in range(len(A)):
        tmp = []
        for j in range(len(A[i])):
            tmp.append(A[i][j] * B[i][j])
        result.append(tmp)

    return result

In [ ]:
print(mulMatrix([[1,2], [2,3]], [[3, 4],[5,6]]))

[[3, 8], [10, 18]]


In [ ]:
def test_1(A, B):
    for i in range(len(A)):
        for j in range(len(A[i])):
            if len(A) != len(B) or len(A[i]) != len(B[i]):
                return "행렬 크기를 맞춰주세요"

In [ ]:
def mulMatrix(A, B):
    result = []

    test_1(A, B)

    for i in range(len(A)):
        tmp = []
        for j in range(len(A[i])):
            tmp.append(A[i][j] * B[i][j])
        result.append(tmp)

    return result

In [ ]:
print(mulMatrix([[1,2, 3], [2,3, 4]], [[3, 4],[5,6]]))

IndexError: list index out of range

In [ ]:
def scalarMulMatrix(A, B):
    result = []

    for i in range(len(A)):
        tmp = []
        for j in range(len(A[i])):
            tmp.append(A[i][j] * B)
        result.append(tmp)

    return result

In [ ]:
print(scalarMulMatrix([[1,2, 3], [2,3, 4]], 2))

[[2, 4, 6], [4, 6, 8]]


In [ ]:
def mulMatrix(A, B):
    result = []

    for i in range(len(A)):
        for j in range(len(A[i])):
            if len(A[i]) != len(B):
                return "행렬 크기를 맞춰주세요"

    for i in range(len(A)):
        tmp = []
        for j in range(len(B[i])):
            tmp.append(A[i][j] * B[j][i])
        result.append(tmp)

    return result

In [ ]:
print(mulMatrix([[1,2], [2,3], [3, 4]], [[3, 4],[5,6], [7, 8]]))

행렬 크기를 맞춰주세요


In [ ]:
def mulMatrix(A, B):
    answer = [[0] * len(B[0]) for row in range(len(A))]

    for row in range(len(A)):
        for col in range(len(B[0])):
            sum = 0
            for i in range(len(A[0])):
                sum += (A[row][i] * B[i][col])
            answer[row][col] = sum
    return answer

In [ ]:
mulMatrix([[1, 2], [3, 4], [5, 6]], [[2, 4], [1, 2]])

[[4, 8], [10, 20], [16, 32]]

In [ ]:
class Matrix:

    def sumMatrix(A, B):
        result = []

        for i in range(len(A)):
            for j in range(len(A[i])):
                if len(A) != len(B) or len(A[i]) != len(B[i]):
                    return "행렬 크기를 맞춰주세요"

        for i in range(len(A)):
            tmp = []
            for j in range(len(A[i])):
                tmp.append(A[i][j] + B[i][j])
            result.append(tmp)

        return result

    def subMatrix(A, B):
        result = []

        for i in range(len(A)):
            for j in range(len(A[i])):
                if len(A) != len(B) or len(A[i]) != len(B[i]):
                    return "행렬 크기를 맞춰주세요"

        for i in range(len(A)):
            tmp = []
            for j in range(len(A[i])):
                tmp.append(A[i][j] - B[i][j])
            result.append(tmp)

        return result

    def scalarMulMatrix(A, B):
        result = []

        for i in range(len(A)):
            tmp = []
            for j in range(len(A[i])):
                tmp.append(A[i][j] * B)
            result.append(tmp)

        return result

    def mulMatrix(A, B):

        if len(A[0]) != len(B):
            return "행렬 크기를 맞춰주세요"

        answer = [[0] * len(B[0]) for row in range(len(A))]

        for row in range(len(A)):
            for col in range(len(B[0])):
                sum = 0
                for i in range(len(A[0])):
                    sum += (A[row][i] * B[i][col])
                answer[row][col] = sum
        return answer

In [ ]:
def mulMatrix(A, B):

    if len(A[0]) != len(B):
        return "행렬 크기를 맞춰주세요"

    answer = [[0] * len(B[0]) for row in range(len(A))]

    for row in range(len(A)):
        for col in range(len(B[0])):
            sum = 0
            for i in range(len(A[0])):
                sum += (A[row][i] * B[i][col])
            answer[row][col] = sum
    return answer

In [ ]:
mulMatrix([[1, 2, 3], [3, 4, 5], [5, 6, 7]], [[2, 4], [1, 2]])

'행렬 크기를 맞춰주세요'